services:
  cert-dumper:
    image: ldez/traefik-certs-dumper:v2.8.3
    container_name: cert-dumper
    restart: unless-stopped
    user: 1001:1001
    environment:
      - TZ=${TZ}
      - ACME_FILE_PATH=/traefik/acme.json
    volumes:
      - ${DATA_ROOT}/cloud/traefik/acme/acme.json:/traefik/acme.json:ro
      - ${DATA_ROOT}/cloud/certs:/output
    command:
      - file
      - --source=/traefik/acme.json
      - --dest=/output
      - --domain-subdir
      - --version=v2
      - --post-hook=echo 'Certificates dumped'